import {
  REACT_APP_API_KEY,
  REACT_APP_AUTH_DOMAIN,
  REACT_APP_DATA_BASE_URL,
  REACT_APP_PROJECT_ID,
  REACT_APP_STORAGE_BUCKET,
  REACT_APP_MESSAGING_SENDER_ID,
  REACT_APP_APP_ID,
  REACT_APP_MEASUREMENT_ID,
} from "@env";

export const API_KEY = REACT_APP_API_KEY;
export const AUTH_DOMAIN = REACT_APP_AUTH_DOMAIN;
export const DATA_BASE_URL = REACT_APP_DATA_BASE_URL;
export const PROJECT_ID = REACT_APP_PROJECT_ID;
export const STORAGE_BUCKET = REACT_APP_STORAGE_BUCKET;
export const MESSAGING_SENDER_ID = REACT_APP_MESSAGING_SENDER_ID;
export const APP_ID = REACT_APP_APP_ID;
export const MEASUREMENT_ID = REACT_APP_MEASUREMENT_ID;

